site_name: Ruta Cultural
site_url: https://carlrodr15.github.io/docs-tienda-os_ejemplo/
theme:
  name: material # Estilo moderno de industria
  palette:
  primary: blue grey
  accent: light green
nav:
  - Inicio: index.md
  - Arquitectura: arquitectura.md
  - API Interactiva: api.md
  - Manual: Manual.md
  - Instalación: Instalación.md
  - Gastronomía y Artesanía: gastronomía-y-artesanías.md
  - Historia: historia.md
  - Mapa interactivo: Mapa-interactivo.md
  - Memoria Técnica (ADRs):
    - 001 Selección de Stack: adrs/ADR-001-Stack.md
    - 002 Estrategia Git: adrs/ADR-002-Estrategia-Git.md
  