openapi: 3.0.0
info:
  title: API Semilleros de Robótica
  description: Interfaz técnica para administrar el inventario de kits y el registro de participantes en los laboratorios STEAM.
  version: 1.0.0
paths:
  /inventario:
    get:
      summary: Consultar inventario de kits.
      description: Devuelve una lista de los equipos (placas, sensores, motores) disponibles en el laboratorio.
      responses:
        '200':
          description: Catálogo obtenido exitosamente.
  /inscripciones:
    post:
      summary: Registrar nuevo integrante.
      description: Añade un estudiante a un grupo de trabajo específico del semillero.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre_completo:
                  type: string
                  example: "Laura Gómez"
                grado:
                  type: string
                  example: "10A"
      responses:
        '201':
          description: Integrante registrado correctamente.
